import json

def inject_models():
    # Load models
    with open('landing/models_catalog.json', 'r') as f:
        models = json.load(f)

    # Load HTML
    with open('landing/index.html', 'r', encoding='utf-8') as f:
        html = f.read()

    # Define the JS block with Truncation & Search
    js_logic = f"""
        // === MODELS CATALOG LOGIC (AUTOGENERATED) ===
        const ALL_MODELS = {json.dumps(models)};
        let selectedCategory = 'All';
        let searchQuery = '';
        let isExpanded = false;

        function renderModels() {{
            const grid = document.getElementById('models-grid');
            const showMoreBtn = document.getElementById('show-more-container');
            
            const filtered = ALL_MODELS.filter(m => {{
                const matchesCategory = selectedCategory === 'All' || m.category === selectedCategory;
                const matchesSearch = m.id.toLowerCase().includes(searchQuery.toLowerCase()) || 
                                     m.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                                     m.provider.toLowerCase().includes(searchQuery.toLowerCase());
                return matchesCategory && matchesSearch;
            }});

            if (filtered.length === 0) {{
                grid.innerHTML = '<div class="empty-state">No models found matching your search.</div>';
                if (showMoreBtn) showMoreBtn.style.display = 'none';
                return;
            }}

            // Truncation logic: only truncate if NOT searching and NOT expanded
            const showAll = isExpanded || searchQuery.length > 0;
            const displayModels = showAll ? filtered : filtered.slice(0, 20);
            
            if (showMoreBtn) {{
                showMoreBtn.style.display = (filtered.length > 20 && !showAll) ? 'block' : 'none';
            }}

            grid.innerHTML = displayModels.map(m => `
                <div class="model-item">
                    <div class="model-badge">${{m.category}}</div>
                    <div class="model-provider">${{m.provider}}</div>
                    <div class="model-name">${{m.name}}</div>
                    <div class="model-footer">
                        <div class="model-price">$${{m.price_usd.toFixed(5)}}</div>
                        <div class="model-action" onclick="copyModelID('${{m.id}}')">copy id</div>
                    </div>
                </div>
            `).join('');
        }}

        function toggleExpand() {{
            isExpanded = true;
            renderModels();
            // Scroll slightly to allow user to see new items
            document.getElementById('models-grid').scrollIntoView({{ behavior: 'smooth', block: 'nearest' }});
        }}

        function copyModelID(id) {{
            navigator.clipboard.writeText(id);
            alert('Copied: ' + id);
        }}

        // Initialize Search & Tabs
        const searchInput = document.getElementById('model-search');
        if (searchInput) {{
            searchInput.addEventListener('input', (e) => {{
                searchQuery = e.target.value;
                renderModels();
            }});
        }}

        document.querySelectorAll('.tab-btn').forEach(btn => {{
            btn.addEventListener('click', () => {{
                document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
                btn.classList.add('active');
                selectedCategory = btn.dataset.category;
                isExpanded = false; // Reset expansion on category change
                renderModels();
            }});
        }});

        // Initial Render
        renderModels();
        // === END MODELS CATALOG LOGIC ===
    """

    # Idempotent replacement: Find everything between markers OR just the placeholder
    marker_start = "// === MODELS CATALOG LOGIC (AUTOGENERATED) ==="
    marker_end = "// === END MODELS CATALOG LOGIC ==="
    placeholder = "// INSERT_CATALOG_HERE"

    if marker_start in html and marker_end in html:
        # Already exists, replace the section
        import re
        pattern = re.escape(marker_start) + ".*?" + re.escape(marker_end)
        new_html = re.sub(pattern, js_logic.strip(), html, flags=re.DOTALL)
    else:
        # First time or placeholder exists
        new_html = html.replace(placeholder, js_logic.strip())

    with open('landing/index.html', 'w', encoding='utf-8') as f:
        f.write(new_html)
    
    print("Successfully synchronized models catalog (idempotent run)")

if __name__ == "__main__":
    inject_models()
